/*
 * run_meltdown.js — Node CLI runner for the PWR CORE-DAMAGE / MELTDOWN PATH
 * BATTERY (test/meltdown_pwr.js): one probe per classic route to core damage,
 * each asserting the *physically correct* endpoint (damage / melt / protected).
 *
 *   node test/run_meltdown.js            run the battery
 *   node test/run_meltdown.js MD-5       run one path by id
 *
 * Gate semantics (strict xfail, same as run_behavior / run_procedures):
 *   - probe passes, not in XFAIL  → PASS  (green)
 *   - probe fails,  in XFAIL      → XFAIL (yellow, known physics gap — gate stays green)
 *   - probe fails,  NOT in XFAIL  → FAIL  (red — a real regression)
 *   - probe passes, in XFAIL      → XPASS (red — the gap was fixed; drop the XFAIL entry)
 *
 * A full run also writes Diagnostic/MELTDOWN_REPORT.md — the endpoint of every
 * path plus the root cause of each open gap (the fix packet).
 */
'use strict';
var path = require('path');
var fs = require('fs');
function load(p) { require(path.join(__dirname, '..', p)); }

[
  'engines/load_mode.js',
  'engines/pwr/pwr_config.js',
  'layers/control/pwr_control.js',
  'engines/pwr/pwr_thermal.js',
  'engines/pwr/pwr_pressurizer.js', 'engines/pwr/pwr_pressurizer2.js',
  'engines/pwr/pwr_primary.js',
  'engines/pwr/pwr_steam_generator.js',
  'engines/pwr/pwr_instruments.js',
  'engines/pwr/pwr_engine.js',
  'test/ops_harness.js',      // RD.OpsTest helpers (test/near/fmt)
  'test/meltdown_pwr.js',
].forEach(load);

var RD = globalThis.RD;
var M = RD.MeltdownPWR;

var GREEN = '\x1b[32m', RED = '\x1b[31m', YEL = '\x1b[33m', DIM = '\x1b[2m',
    CYAN = '\x1b[36m', RST = '\x1b[0m', BOLD = '\x1b[1m';

var idArg = process.argv[2];
var results = idArg
  ? (M.probes[idArg] ? [(function () { var r = M.probes[idArg](); r.id = idArg; return r; })()]
     : (console.log('unknown path id: ' + idArg), process.exit(2)))
  : M.runAll();

var nPass = 0, nXfail = 0, nFail = 0, nXpass = 0;
var gapRows = [];

console.log('\n' + BOLD + '════════ PWR MELTDOWN-PATH BATTERY ════════' + RST);

results.forEach(function (r) {
  var expected = Object.prototype.hasOwnProperty.call(M.XFAIL, r.id);
  var verdict, color;
  if (r.pass && !expected)       { verdict = 'PASS';  color = GREEN; nPass++; }
  else if (!r.pass && expected)  { verdict = 'XFAIL'; color = YEL;   nXfail++; }
  else if (!r.pass && !expected) { verdict = 'FAIL';  color = RED;   nFail++; }
  else                           { verdict = 'XPASS'; color = RED;   nXpass++; }

  console.log('\n' + color + BOLD + verdict + RST + '  ' + BOLD + r.name + RST);
  r.checks.forEach(function (c) {
    var mark = c.info ? CYAN + '  ▸' + RST : (c.pass ? GREEN + '  ✓' + RST : (expected ? YEL : RED) + '  ✗' + RST);
    var line = mark + ' ' + c.desc;
    if (c.info) line += DIM + '  = ' + c.observed + RST;
    else if (!c.pass) line += DIM + '  [expected ' + c.expected + ', observed ' + c.observed + ']' + RST;
    else line += DIM + '  (' + c.observed + ')' + RST;
    console.log(line);
  });

  if (!r.pass || verdict === 'XPASS') {
    gapRows.push({ id: r.id, name: r.name, verdict: verdict, known: expected ? M.XFAIL[r.id] : null,
      failed: r.checks.filter(function (c) { return !c.info && !c.pass; }),
      infos: r.checks.filter(function (c) { return c.info; }) });
  }
});

console.log('\n' + BOLD + '──────────────────────────────────────────' + RST);
console.log(BOLD + 'Paths: ' + RST + GREEN + nPass + ' pass' + RST +
  ', ' + YEL + nXfail + ' xfail (known physics gaps)' + RST +
  (nFail ? ', ' + RED + nFail + ' FAIL' + RST : '') +
  (nXpass ? ', ' + RED + nXpass + ' XPASS (stale annotation)' + RST : ''));

// -------------------------------------------------------- report (full run only)
if (!idArg) {
  var diagDir = path.join(__dirname, '..', 'Diagnostic');
  try {
    fs.mkdirSync(diagDir, { recursive: true });
    var md = [];
    md.push('# PWR Meltdown-Path Report');
    md.push('');
    md.push('Auto-generated by `node test/run_meltdown.js`. One entry per classic route');
    md.push('to core damage; each asserts the physically correct endpoint. Do not hand-edit.');
    md.push('');
    md.push('Result: ' + nPass + ' pass, ' + nXfail + ' known gaps (xfail)' +
      (nFail ? ', ' + nFail + ' UNEXPECTED FAIL' : '') +
      (nXpass ? ', ' + nXpass + ' XPASS (stale annotation)' : '') + '.');
    md.push('');
    if (!gapRows.length) {
      md.push('**No open gaps — every meltdown path reaches its correct endpoint.**');
    }
    gapRows.forEach(function (g) {
      md.push('## ' + g.id + ' — ' + g.name + (g.verdict !== 'XFAIL' ? '  (' + g.verdict + ')' : ''));
      if (g.known) { md.push('*Root cause:* ' + g.known); md.push(''); }
      g.failed.forEach(function (c) {
        md.push('- **' + c.desc + '** — required `' + c.expected + '`, observed `' + c.observed + '`');
      });
      g.infos.forEach(function (c) { md.push('- endpoint: ' + c.desc + ' = `' + c.observed + '`'); });
      md.push('');
    });
    var repPath = path.join(diagDir, 'MELTDOWN_REPORT.md');
    fs.writeFileSync(repPath, md.join('\n'));
    console.log(DIM + 'report → ' + repPath + RST);
  } catch (e) { console.log(DIM + 'report write skipped: ' + e.message + RST); }
}

process.exit((nFail || nXpass) ? 1 : 0);
