/*
 * verify_pzr2_loadlists.js — every carrier of the pressurizer loads BOTH models, in order.
 *
 * WHY THIS GATE EXISTS (#472 phase 3a)
 * ------------------------------------
 * The rebuild is built alongside the shipped model and selected at load time. That makes
 * the LOAD LIST part of the switch, and a load list is exactly the kind of thing that gets
 * one entry and not the other: ~33 files name `pwr_pressurizer.js`, each in its own
 * hand-maintained array or <script> block, and a runner that forgets the v2 line silently
 * tests v1 WHILE STAMPED v2 — a green gate measuring the wrong plant, which is the failure
 * class CLAUDE.md's standing list already names twice ("a claim about COVERAGE is an
 * unmeasured claim"; "a passing check can be HOLLOW").
 *
 * The ORDER half matters just as much and for a sharper reason: `pwr_engine.js:22` caches
 * `PZ = RD.pwrPressurizer` at load time, so v2 loaded after the engine swaps the global
 * for the late-binding readers (`pwr_primary.js:304`, `pwr_instruments.js:240`) while the
 * engine keeps calling v1 — the plant then runs HALF of each model. pwr_pressurizer2.js
 * throws on that, but only when the flag is ON; this gate catches it with the flag off,
 * which is the state the tree ships in.
 *
 * DISPOSABLE. Delete this file, its BASELINES entry and the v2 load lines at cutover, when
 * the rebuilt body moves into `pwr_pressurizer.js` and there is one model again.
 */
'use strict';
var fs = require('fs');
var path = require('path');

var ROOT = path.resolve(__dirname, '..');
var GREEN = '\x1b[32m', RED = '\x1b[31m', DIM = '\x1b[2m', BOLD = '\x1b[1m', RST = '\x1b[0m';

// Directories that are BUILD OUTPUT or scratch, not source. `dist/` and `dist-site/` are
// generated by make_portable/the site build and carry their own copies, and so is
// `download/` (site/make_download.js) — a stale portable build there reddened this gate on
// the release tree while the same commit was green on a lane that had never built one; `inbox/` is
// gitignored drafts. Scanning them would gate artifacts instead of sources.
var SKIP = /^(node_modules|dist|dist-site|download|inbox|terminals|mcps|\.git)(\/|$)/;

function walk(dir, out) {
  fs.readdirSync(dir, { withFileTypes: true }).forEach(function (e) {
    var abs = path.join(dir, e.name);
    var rel = path.relative(ROOT, abs).replace(/\\/g, '/');
    if (SKIP.test(rel)) return;
    if (e.isDirectory()) walk(abs, out);
    else if (/\.(js|html)$/.test(e.name)) out.push(rel);
  });
  return out;
}

var checks = [];
function ck(desc, observed, pass, expected) {
  checks.push({ desc: desc, observed: observed, pass: !!pass, expected: expected });
}

var files = walk(ROOT, []);

// A LOAD is a quoted path ending in the filename — the form both `require` arrays and
// <script src> use. Prose mentions in comments (ui/app.js, pwr_board_wiring.js) do not
// match, which is the point: a comment naming the file is not a carrier. This is the
// "a static gate reading source must strip COMMENTS" trap from CLAUDE.md, solved by
// requiring the quote rather than by stripping.
var V1 = /['"][^'"]*pwr_pressurizer\.js['"]/;
var V2 = /['"][^'"]*pwr_pressurizer2\.js['"]/;
var ENGINE = /['"][^'"]*pwr_engine\.js['"]/;

var carriers = [], missing = [], misordered = [];

files.forEach(function (rel) {
  var txt = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  if (!V1.test(txt)) return;
  // Two files NAME the pressurizer sources without loading them, and both are excluded by
  // path rather than by cleverness: the v2 module (its header quotes the v1 filename) and
  // THIS GATE (its comments quote both). A scanner that matches its own explanation is a
  // trap this file has now hit twice — once here and once in the swap check below — so the
  // exclusion is explicit and named rather than a regex refinement that would drift.
  if (rel === 'engines/pwr/pwr_pressurizer2.js') return;
  if (rel === 'test/verify_pzr2_loadlists.js') return;
  carriers.push(rel);

  if (!V2.test(txt)) { missing.push(rel); return; }

  // Order: v2 must appear after v1 (it delegates to it) and BEFORE the engine.
  var iV1 = txt.search(V1), iV2 = txt.search(V2), iEng = txt.search(ENGINE);
  if (iV2 < iV1) misordered.push(rel + ' (v2 before v1)');
  else if (iEng >= 0 && iV2 > iEng) misordered.push(rel + ' (v2 after pwr_engine.js — the :22 cache trap)');
});

ck('carriers found (the scan is not returning an empty set)', String(carriers.length),
  carriers.length >= 30, '>= 30');
ck('every pwr_pressurizer.js carrier also loads pwr_pressurizer2.js',
  missing.length ? missing.join(', ') : 'all ' + carriers.length,
  missing.length === 0, 'none missing');
ck('v2 loads after v1 and before pwr_engine.js in every carrier',
  misordered.length ? misordered.join(', ') : 'all ' + carriers.length,
  misordered.length === 0, 'correct order');

// The selector must be the ONLY reader of the enabled flag: a second reader turns one
// switch into two and the plant can run half of each model.
// ONE SWAP, AND THIS CHECK REPLACES A HOLLOW ONE — read the story, it cost nothing to find
// and would have cost a lot to trust.
//
// The first version of this check asserted "`pressurizer2.enabled` is read in exactly one
// place". It PASSED, and it was hollow twice over. (1) The only occurrence of that string
// in the selector is A COMMENT — the real read is `cfg2.enabled === 1` through an alias the
// regex cannot see, so the check was measuring prose. That is CLAUDE.md's standing trap
// verbatim: "a static gate reading source must strip COMMENTS". (2) The invariant was wrong
// anyway: the A/B harnesses (`measure_stack --pzr2`, `_perturb_child` via RD_PZR2) legally
// WRITE that flag, so counting writers as readers reddened it the moment the harnesses
// landed. A check whose green came from a comment and whose red came from correct code is
// worth deleting, not repairing.
//
// What actually matters is narrower and cannot be aliased away: **who replaces the global
// the engine binds to.** Exactly two files may assign `RD.pwrPressurizer` — v1 exporting
// itself, and v2 swapping itself in. A third assignment anywhere is the half-of-each-model
// failure this gate exists to prevent.
function stripComments(src) {
  return src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:'"\\])\/\/[^\n]*/g, '$1');
}
var swappers = files.filter(function (rel) {
  if (rel === 'test/verify_pzr2_loadlists.js') return false;   // this file names it in prose
  return /RD\.pwrPressurizer\s*=[^=]/.test(stripComments(fs.readFileSync(path.join(ROOT, rel), 'utf8')));
});
swappers.sort();
ck('exactly two files assign RD.pwrPressurizer (v1 exports, v2 swaps)',
  swappers.join(', ') || 'none',
  swappers.length === 2 &&
  swappers[0] === 'engines/pwr/pwr_pressurizer.js' &&
  swappers[1] === 'engines/pwr/pwr_pressurizer2.js',
  'pwr_pressurizer.js + pwr_pressurizer2.js only');

var failed = checks.filter(function (c) { return !c.pass; });
console.log('\n' + BOLD + '════════ PZR2 LOAD-LIST PARITY ════════' + RST);
checks.forEach(function (c) {
  console.log((c.pass ? GREEN + '  ✓' : RED + '  ✗') + RST + ' ' + c.desc +
    DIM + (c.pass ? '  (' + c.observed + ')' : '  [expected ' + c.expected + ', observed ' + c.observed + ']') + RST);
});
console.log('\n' + BOLD + '──────────────────────────────────────────' + RST);
console.log(BOLD + (failed.length ? RED : GREEN) + 'PZR2 LOADLISTS: ' +
  (failed.length ? failed.length + ' failed' : 'OK') + RST +
  DIM + '  ' + checks.length + ' checks, ' + failed.length + ' failed' + RST);
process.exit(failed.length ? 1 : 0);
