/*
 * tools/pack_manuals.js — packs the Manuals/*.md operator set into
 * ui/manual_md.js (→ RD.MANUAL_MD), so the in-app Operator's Manual renders the
 * SAME markdown files that live in the repo. Single source of truth: edit
 * Manuals/*.md, re-run this, and the site follows. A .js pack (not fetch) so
 * the app keeps working from file:// like every other data artifact.
 *
 * Re-run after editing any Manuals/*.md:  node tools/pack_manuals.js
 *
 * The three dev-facing logs (ISSUES_AND_FINDINGS, CAMPAIGN_MANUAL_DISCREPANCIES,
 * CAMPAIGN_MODE_ALIGNMENT_SPEC) are deliberately NOT packed — they are working
 * documents, not operator documentation.
 */
'use strict';
var fs = require('fs'), path = require('path');

var ROOT = path.join(__dirname, '..');
var SRC = path.join(ROOT, 'Manuals');

// Reader order: orientation first, numbered set, revision history last.
var DOCS = [
  'README.md',
  '01_GENERAL_DESCRIPTION.md',
  '02_SIMULATOR_USER_GUIDE.md',
  '03_CONTROLS_AND_INDICATIONS.md',
  '04_NORMAL_OPERATIONS.md',
  '05_MODE_TRANSITIONS.md',
  '06_ALARM_RESPONSE.md',
  '07_ABNORMAL_EMERGENCY.md',
  '08_ACCIDENT_TMI.md',
  '09_SETPOINTS_LIMITS.md',
  '10_GLOSSARY.md',
  '11_CAMPAIGN_CROSSWALK.md',
  '12_SIM_PHYSICS.md',
  '00_REVISION_HISTORY.md',
];

function labelFor(file, md) {
  if (file === 'README.md') return 'Read Me First';
  var m = /^#\s+(.+)$/m.exec(md);
  var t = m ? m[1].trim() : file.replace(/\.md$/, '');
  // "01 — Plant General Description" → "01 · Plant General Description"
  return t.replace(/\s+[—–-]\s+/, ' · ');
}

var docs = DOCS.map(function (file) {
  var md = fs.readFileSync(path.join(SRC, file), 'utf8').replace(/^﻿/, '');
  return {
    id: file.replace(/\.md$/, '').toLowerCase(),
    file: file,
    label: labelFor(file, md),
    md: md,
  };
});

var MANUAL_MD = {
  pwr: {
    plant_label: 'SLS-100 — Pressurized Water Reactor',
    docs: docs,
  },
};

var body = ';(function (RD) {\n  "use strict";\n' +
  '  // GENERATED by tools/pack_manuals.js from Manuals/*.md — do not hand-edit.\n' +
  '  RD.MANUAL_MD = ' + JSON.stringify(MANUAL_MD, null, 2).replace(/\n/g, '\n  ') + ';\n' +
  '})(globalThis.RD || (globalThis.RD = {}));\n';

fs.writeFileSync(path.join(ROOT, 'ui', 'manual_md.js'), body);
console.log('Wrote ui/manual_md.js (' + (body.length / 1024).toFixed(1) + ' KB, ' + docs.length + ' docs)');
docs.forEach(function (d) { console.log('  ' + d.id + ': ' + d.label + ' (' + (d.md.length / 1024).toFixed(1) + ' KB)'); });
