/* tools/pack_site_docs.js — pack the public Disclaimer / License / Changelog
 * pages into ui/site_docs.js so the control room can show them offline.
 *
 *   node tools/pack_site_docs.js
 *
 * WHY. The portable single-file build is only the control room (ui/shell.html).
 * Recipients with no network had no route to the alpha disclaimer, the licence,
 * or the player-facing changelog (#259). The manuals already use this pack
 * pattern (pack_manuals.js → manual_md.js); same idea here — edit legal.html /
 * changelog.html, re-run this, and Settings → About ships the same text.
 *
 * Sources of truth: legal.html (disclaimer + licence sections) and
 * changelog.html (player-facing log entries). Do not hand-edit ui/site_docs.js.
 */
'use strict';
var fs = require('fs');
var path = require('path');

var ROOT = path.join(__dirname, '..');
var OUT = path.join(ROOT, 'ui', 'site_docs.js');

function read(name) {
  return fs.readFileSync(path.join(ROOT, name), 'utf8').replace(/^\uFEFF/, '');
}

function mainInner(html) {
  var m = /<main\b[^>]*class="[^"]*\bpage\b[^"]*"[^>]*>([\s\S]*?)<\/main>/i.exec(html);
  if (!m) throw new Error('no <main class="page"> in source');
  return m[1].trim();
}

// Drop HTML comments (changelog's ADDING AN ENTRY template is a multi-line one).
function stripComments(s) {
  return s.replace(/<!--[\s\S]*?-->/g, '');
}

// Pull everything from the first <h2> whose text matches re through the end of
// that section's following siblings, stopping at the next <h2> that does NOT
// match (or end). Used to split legal.html into disclaimer vs licence bodies.
function sectionsFrom(html, startRe, stopRe) {
  var h2 = /<h2\b[^>]*>[\s\S]*?<\/h2>/gi;
  var matches = [];
  var m;
  while ((m = h2.exec(html)) !== null) {
    matches.push({ index: m.index, end: m.index + m[0].length, text: m[0].replace(/<[^>]+>/g, '') });
  }
  var start = -1;
  var stop = html.length;
  for (var i = 0; i < matches.length; i++) {
    if (start < 0 && startRe.test(matches[i].text)) {
      start = matches[i].index;
      continue;
    }
    if (start >= 0 && stopRe && stopRe.test(matches[i].text)) {
      stop = matches[i].index;
      break;
    }
  }
  if (start < 0) throw new Error('section not found: ' + startRe);
  return html.slice(start, stop).trim();
}

function beforeFirstH2(html) {
  var i = html.search(/<h2\b/i);
  return i < 0 ? html.trim() : html.slice(0, i).trim();
}

// Alpha banner the landing page carries — the offline recipient needs it most.
var ALPHA_NOTE =
  '<div class="doc-alpha">\uD83D\uDEA7 Alpha \u2014 desktop or laptop only \u2014 not for phones or tablets yet</div>';

var legalMain = stripComments(mainInner(read('legal.html')));
var changeMain = stripComments(mainInner(read('changelog.html')));

// Disclaimer: notice + educational/safety sections (1–4). Skip the page <h1>/<lede>
// and the licensing block that belongs in the License popup.
var legalLead = beforeFirstH2(legalMain);
// Drop the page title/lede (h1 + first lede p) — the modal has its own title.
legalLead = legalLead
  .replace(/<h1\b[^>]*>[\s\S]*?<\/h1>/i, '')
  .replace(/<p\b[^>]*class="[^"]*\blede\b[^"]*"[^>]*>[\s\S]*?<\/p>/i, '')
  .trim();
var disclaimerBody =
  ALPHA_NOTE + '\n' +
  legalLead + '\n' +
  sectionsFrom(legalMain, /^\s*1\.\s/i, /^\s*5\.\s/);

// License: sections 5–6 (AGPL + CC BY + attribution). Drop privacy/contact
// (7–8) — those need the live site and aren't licence terms.
var licenseBody = sectionsFrom(legalMain, /^\s*5\.\s/, /^\s*7\.\s/);

// Changelog: keep the lede + every log-entry article; drop the page <h1>.
var changelogBody = changeMain
  .replace(/<h1\b[^>]*>[\s\S]*?<\/h1>/i, '')
  .trim();

var docs = {
  disclaimer: {
    title: 'Disclaimer',
    html: disclaimerBody,
  },
  license: {
    title: 'License',
    html: licenseBody,
  },
  changelog: {
    title: 'Changelog',
    html: changelogBody,
  },
};

// Sanity: each body must carry a distinctive phrase so a silent empty pack fails loud.
var MUST = {
  disclaimer: /educational simulation/i,
  license: /AGPL/i,
  changelog: /log-entry|Alpha\s+\d/i,
};
Object.keys(MUST).forEach(function (k) {
  if (!docs[k].html || !MUST[k].test(docs[k].html)) {
    throw new Error('pack_site_docs: ' + k + ' body looks empty or wrong');
  }
});

var out =
  '/* GENERATED by tools/pack_site_docs.js — do not hand-edit.\n' +
  ' * Source: legal.html (disclaimer + license) and changelog.html.\n' +
  ' * Re-run after editing either page so Settings \u2192 About stays current offline (#259).\n' +
  ' */\n' +
  '(function (G) {\n' +
  '  "use strict";\n' +
  '  G.RD = G.RD || {};\n' +
  '  G.RD.SITE_DOCS = ' + JSON.stringify(docs, null, 2) + ';\n' +
  '})(typeof globalThis !== "undefined" ? globalThis : this);\n';

fs.writeFileSync(OUT, out);
console.log('wrote ' + path.relative(ROOT, OUT) +
  '  disclaimer=' + docs.disclaimer.html.length +
  'B  license=' + docs.license.html.length +
  'B  changelog=' + docs.changelog.html.length + 'B');
